### ISSUE TITLE
User Review List Only One Page

### ISSUE THREAD

**Issue by bksubhuti** [dhammacakka/pm12e#43]
User wishes to review words.  Review list is limited to one page.
Can this be increased?

**Comment by cruncheranalyzer** [comment]
Review list items are limited to the last 10 items only. As a user, I would like to view all of my edited items and their status.

Please add 'send to expert' column to UI table, if your table has that flag. so that I can easily find my 'send to expert' related  edited items. I may have a few 'send to expert' items out of my 100 edited items.

**Comment by bksubhuti** [comment]
fixed
